spring:
  profiles:
    group:
      "local": "local-db,local-server"
      "test":  "prod-db,prod-server"
      "prod": "prod-db,prod-server"

#JWT secret
spring.jwt.secret: ${JWT_SECRET}


logging.level.org.hibernate: info
management.security.enabled: false

---

spring.config.activate.on-profile: local-db
spring.datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
    url: jdbc:mariadb://host.docker.internal:3306/portfolio?allowPublicKeyRetrieval=true&useSSL=false

---

spring.config.activate.on-profile: prod-db

spring.datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: ${DB_USER}
    password: ${DB_PW}
    url: ${DB_URL}

---

spring.config.active.on-profile: prod-server

server.port: 9001

---

spring.config.activate.on-profile: local-server

server.port: 8080
---