CREATE TABLE contact (
    id NUMBER(10) NOT NULL,
    name VARCHAR2(255 CHAR) NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL,
    message VARCHAR2(255 CHAR) NOT NULL,
    contact_date TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE project (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    category VARCHAR2(255 CHAR) NOT NULL,
    name VARCHAR2(255 CHAR) NOT NULL,
    img VARCHAR2(255 CHAR),
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE program (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    name VARCHAR2(255 CHAR) NOT NULL,
    icon VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT pk_program PRIMARY KEY (id)
);

CREATE TABLE project_program (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    program_id NUMBER(10) NOT NULL,
    project_id NUMBER(10) NOT NULL,
    link VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT pk_project_program PRIMARY KEY (id)
);

CREATE INDEX idx_project_program_program_id ON project_program (program_id);
CREATE INDEX idx_project_program_project_id ON project_program (project_id);
